.editorconfig, .flake8, .github/workflows/ci.yml, README.md, decoy/__init__.py, decoy/matchers.py, decoy/mock.py, decoy/registry.py, decoy/stub.py, docs/why.md, mkdocs.yml, poetry.lock, pyproject.toml, tests/common.py, tests/test_decoy.py, tests/test_verify.py, tests/test_when.py
This PR:
- Ensures mocks can be nested
- Adds missing `py.typed` file that was preventing mypy from picking up types in the end-user environment
Since I'm making changes, it also includes the following fixes:
- Fix docs indent problems by always using 4-space tabs in Markdown
- Add missing classifiers to pyproject.toml
- Ensure CI can always deploy docs using `--force`
=> fix: allow nested mocks and typing

README.md, decoy/mypy.py, mkdocs.yml, mypy.ini, poetry.lock, pyproject.toml, tests/test_verify.py, tests/typing/test_mypy_plugin.yml, tests/typing/test_typing.yml
Closes #5. See ticket for details.
In addition to the mypy plugin to suppress spurious `func-returns-value` errors on rehearsals, this PR also adds...
- Tests for that plugin
- Tests for the spy and stub typing
...via the [pytest-mypy-plugins](https://github.com/typeddjango/pytest-mypy-plugins) library
=> feat: add mypy plugin

decoy/__init__.py, decoy/matchers.py, decoy/spy.py, poetry.lock, tests/test_registry.py, tests/test_spy.py, tests/test_verify.py
Closes #4. See ticket for details. This PR adds assertion messages to failed `verify` calls:
```
E       AssertionError: Expected call:
E       	some_func('fizzbuzz')
E       Found 2 calls:
E       1.	some_func('hello')
E       2.	some_func('goodbye')
```
=> feat(verify): add proper assertion messages

decoy/spy.py, tests/test_spy.py
Fixes #8. See issue for more details
=> fix(spy): allow spy creation when type hints cannot be resolved

decoy/__init__.py, decoy/registry.py, decoy/warnings.py, docs/api.md, tests/conftest.py, tests/test_warnings.py, tests/test_when.py
This PR adds a warning (via the built-in [warnings](https://docs.python.org/3/library/warnings.html#module-warnings) module) if a stub is called with arguments that do not match a previous rehearsal.
Primarily, this serves as a quality of life upgrade to help test writers get to passing tests a little more quickly, and closes #14.
The decision to log a warning instead of asserting is intentional: it is my opinion that a stub should not in the business of providing assertions and failing the test. Warnings provide a happy middle path, where a test writer has a clear indication if they messed up their arguments somehow, but isn't forced to interact with a stub correctly to get the tests to pass as part of a TDD flow.
Warnings may be disabled at the `Decoy` container level using: …
=> feat(when): warn if stub is called with args that do not match

decoy/__init__.py, decoy/registry.py, decoy/warnings.py, docs/api.md, tests/conftest.py, tests/test_warnings.py, tests/test_when.py
This PR is a second attempt at #15. The previous attempt had a bug where stub configuration rehearsals would incorrectly trigger the `MissingStubWarning`. That PR was reverted.
This PR corrects the bug that was present in the initial implementation. Closes #14 for real this time
=> feat(when): warn if stub is called incorrectly

decoy/__init__.py, tests/typing/test_typing.yml
This PR simplifies the typing of `create_decoy` to allow ABC's to be passed in as `spec` without complaint. See #13 for details and background
=> fix(typing): ensure create_decoy typing accepts ABC as spec

README.md, decoy/__init__.py, docs/usage/create.md, docs/usage/errors-and-warnings.md, docs/usage/matchers.md, docs/usage/verify.md, docs/usage/when.md, docs/why.md, tests/test_call_handler.py, tests/test_core.py, tests/test_decoy.py, tests/typing/test_typing.yml
This PR deprecates the `create_decoy` and `create_decoy_func` methods in favor of a much more straightforward `mock` method.
```python
decoy.create_decoy(spec=SomeClass)
decoy.create_decoy_func(spec=some_func)
decoy.create_decoy_func()
decoy.mock(cls=SomeClass)
decoy.mock(func=some_func)
decoy.mock()
```
=> feat: add mock method for creating mocks

decoy/spy.py, tests/test_spy.py
=> fix(spy): set child specs even if parents' type hints can't be resolved

decoy/spy.py, mkdocs.yml, tests/test_spy.py
After [prompting from @SyntaxColoring](https://github.com/Opentrons/opentrons/pull/8161#discussion_r680034418), I wrote a test to see if Decoy correctly matched `inspect.signature` for `@staticmethod`'s of spec classes. Turns out it doesn't!
This PR fixes that bug.
=> fix(spy): match inspect.signature for staticmethods

decoy/spy.py, poetry.lock, pyproject.toml
Also ensure that `coverage.py` doesn't erroneously mark `typing.overload` method definitions as uncovered
=> refactor(spy): remove ununsed try/catch

decoy/__init__.py, decoy/core.py, decoy/errors.py, decoy/stringify.py, decoy/verifier.py, tests/test_errors.py
- Ensure verify error message is helpful when actual call count matches the `times` argument
- Use `__tracebackhide__` to hide Decoy code from pytest traceback
=> fix(verify): improve verify traceback and error messsage

decoy/matchers.py, tests/test_matchers.py, tests/typing/test_typing.yml
`matchers.ErrorMatching` is now typed to return the specific error type passed in rather than simply returning an `Exception`
=> fix(matchers): ensure ErrorMatching return type matches spec

decoy/spy.py, decoy/warnings.py, docs/usage/errors-and-warnings.md, tests/common.py, tests/test_decoy.py, tests/test_spy.py
=> feat: match args leniently according to spec signature

CONTRIBUTING.md, decoy/__init__.py, decoy/call_handler.py, decoy/context_managers.py, decoy/core.py, decoy/pytest_plugin.py, decoy/spy.py, decoy/stub_store.py, decoy/types.py, decoy/warning_checker.py, docs/advanced/context-managers.md, docs/usage/matchers.md, mkdocs.yml, tests/test_call_handler.py, tests/test_core.py, tests/test_decoy.py, tests/test_pytest_plugin.py, tests/test_spy.py, tests/typing/test_typing.yml
Closes #58
- Added `Stub.then_enter_with` method for returning context manager wrapped values
- Intended use case: mocking functions/methods decorated with `@contextlib.contextmanager`
- Added support for mocking `__enter__` and `__exit__` methods
- Intended use case: mocking context manager classes directly
- Added advanced documentation for mocking context manager interfaces
Note: the addition of `then_enter_with` was initially unexpected, but solution proposed in #58 of simply using `contextlib.nullcontext` did not typecheck properly, and was a little difficult to read. I think the `then_enter_with` method, which typechecks well, is also more communicative of intent when reading tests
=> feat(when): add ContextManager mocking support

decoy/__init__.py, decoy/call_handler.py, decoy/core.py, decoy/spec.py, decoy/spy.py, decoy/spy_log.py, decoy/stub_store.py, docs/api.md, docs/usage/verify.md, mkdocs.yml, tests/common.py, tests/test_call_handler.py, tests/test_core.py, tests/test_decoy.py, tests/test_spec.py, tests/test_spy.py, tests/test_spy_calls.py, tests/test_spy_log.py, tests/test_stub_store.py
This PR started as work on #18. However, the `Spy` had built up a fair amount of complexity that made it difficult to add new features.
In advance of property access mocking, the PR moves most of the complexity to a new `Spec` class and reworks the `Spy` class to be more clearly a collaborator object.
=> refactor: move spec inspection logic to Spec class

decoy/spec.py, tests/common.py, tests/test_spec.py
Mocks of callable classes (classes with `__call__` methods defined) were producing incorrect signatures: the signature of `__init__` rather than `__call__` would be used.
This PR fixes that issue. As a side effect, the Decoy test suite will no longer produce `IncorrectCallWarning`s on Python >= 3.9.
=> fix(spy): ensure class signature uses __call__

decoy/warning_checker.py, tests/test_warning_checker.py
=> fix(warnings): do not trigger MiscalledStubWarnings from prop events

decoy/spec.py, tests/common.py, tests/test_spec.py
Trying to get the signature of an `@property` that is typed with something like `int` or `str` will cause decoy to raise an error from `inspect.signature`. This PR fixes that issue.
This was a regression introduced in #108 which narrowed the `except` around `inspect.signature` from `Exception` to `TypeError`. As stated in the Python docs, [`inspect.signature`](https://docs.python.org/3/library/inspect.html#inspect.signature):
> Raises [ValueError](https://docs.python.org/3/library/exceptions.html#ValueError) if no signature can be provided, and [TypeError](https://docs.python.org/3/library/exceptions.html#TypeError) if that type of object is not supported.
=> fix(spy): handle properties that return primitive types

decoy/spec.py, tests/common.py, tests/test_spec.py
Unwrap specs and child specs during mock source inspection to better support stuff like `functools.lru_cache`. Closes #133
=> fix(spy): follow __wrapped__ when getting specs and signatures

decoy/spy_core.py, tests/fixtures.py, tests/test_spy_core.py
=> fix(spy): resolve source to origin of GenericAlias

README.md
The build status badge in the readme is currently showing an error, apparently because of a (reasonable) breaking change in the https://shields.io service. This PR attempts to fix it according to the instructions in badges/shields#8671.
=> docs(readme): update URL for build status badge

.github/workflows/ci.yml, decoy/spy_core.py, tests/fixtures.py, tests/test_spy_core.py
Closes #146. Similarly to how we handle `staticmethod`, this PR gets the `.__func__` attribute of a `classmethod` to use at a `Spy`'s source specification, which works around a bug (?) in Python where `inspect.iscoroutinefunction` returns `False` on Python <3.10 for async `@classmethod` functions.
This PR also drops Python 3.6 from the CI matrix due to GitHub dropping it from the `ubuntu-latest` runner since it EOL'd. Python 3.6 support is not officially dropped from Decoy (which I would put behind a major version bump) but ensuring proper behavior on 3.6 will be harder moving forward
=> fix(spy): use classmethod `__func__` source for async detection

decoy/spy.py
Closes #144 by reducing the risk of attribute collision
=> fix(spy): prefix internal properties with `_decoy`

.github/actions/setup/action.yml
Collapses the "check" and "install" steps to avoid annoying "process exited with..." failure annotations for expected behavior when the action cache didn't hit
=> ci: collapse poetry "check" and "install" steps

decoy/warning_checker.py
#164 upgraded ruff to include more flake8 bugbear errors, which highlighted that the `stacklevel` argument to `warnings.warn` is not used by the warning checker. This results in warnings being attached to an unhelpful decoy-internal call-site.
This PR uses the `stacklevel` argument of `warnings.warn` to trigger the warnings at whatever level called `decoy.reset`. For pytest usage, this results in something like the following:
```shell
/Users/mc/projects/decoy/decoy/warning_checker.py:60: MiscalledStubWarning: Stub was called but no matching rehearsal found.
Found 1 rehearsal:
1.	stub(1, 2, 3)
Found 1 call:
1.	stub(4, 5, 6)
warn(MiscalledStubWarning(calls=unmatched, rehearsals=past_stubs))
/Users/mc/projects/decoy/decoy/pytest_plugin.py:32: MiscalledStubWarning: Stub was called but no …
```
=> fix(warnings): trigger `reset` warnings at a better stack level

decoy/spy_events.py, tests/test_spy_events.py
Thanks to #200, we found a bug in how rehearsals are compared to actual calls. Previously, the check looked something like:
```py
if call_arg == rehearsal_arg:
...
```
This ordering gives preference to `call_arg.__eq__` if it exists, which means if `rehearsal_arg` is a matcher, `rehearsal_arg.__eq__` isn't used. Oops!
- Switch order of rehearsal <> call comparisons so rehearsals are always on the left side, giving their `__eq__` methods priority, if they exist
=> fix(spy): ensure __eq__ of rehearsal arg is preferred

.github/actions/setup/action.yml, .github/workflows/ci.yml, decoy/__init__.py, decoy/errors.py, decoy/matchers.py, decoy/warnings.py, docs/usage/errors-and-warnings.md, poetry.lock, pyproject.toml
This PR makes sure we're using the latest available mkdocs tools by scoping them to `>=3.8`, since several libraries involved have dropped 3.7 support. We use 3.11 for the docs build, so this is acceptable.
It also:
- Adds Python 3.12 to the test matrix
- Upgrades black to latest
- Upgrades mypy to latest
=> chore: upgrade docs dependencies and fix warnings

decoy/spy_core.py, decoy/warnings.py, docs/usage/errors-and-warnings.md, tests/test_spy_core.py
This PR introduces a `MissingSpecAttributeWarning` that will be thrown if you try to use an attribute of a mock that does not exist on its spec. Closes #204.
In the next major version of Decoy, this warning will become an error.
=> feat(spy): warn if mock used with a missing attribute

decoy/warning_checker.py, decoy/warnings.py, tests/test_call_handler.py
#204 raised a couple questions about when Decoy chooses to emit errors and warnings, one of which is addressed by #218. The second question asks:
> [Should Decoy complain if] we try calling a method that is part of the mocked spec which is not mocked?
Currently, Decoy will not complain in this scenario. It will issue a `MiscalledStubWarning` if and only if the mock in question is used at least once with `decoy.when`, which acts as a marker for a test to say "I care about this dependency". This PR comes out of an investigation into the feasibility of enabling a `MiscalledStubWarning` even if the mock is fully unconfigured. In the course of answering this question:
- I reworked this portion of the warning checker
- **I decided the answer is still no**
Issuing a warning in this case forces …
=> refactor(warnings): rework MiscalledStubWarning checker for clarity

.github/actions/setup/action.yml, .github/workflows/ci.yml, decoy/spy_core.py, tests/fixtures.py, tests/test_spy_core.py
=> fix(warnings): avoid `MissingSpecAttributeWarning` if property type is missing or optional

decoy/matchers.py, tests/test_matchers.py
When using decoy.when across multiple test cases, you may want the mock to return a result regardless of the argument values—even if some are None. To handle all combinations, you'd typically need to define multiple matchers like:
```
decoy.when(
mock_instance.execute(
arg1=matchers.Anything(),
arg2=None,
)
).then_return(self.some_result)
decoy.when(
mock_instance.execute(
arg1=matchers.Anything(),
arg2=matchers.Anything(),
)
).then_return(self.some_result)
decoy.when(
mock_instance.execute(
arg1=None,
arg2=matchers.Anything(),
)
).then_return(self.some_result)
```
This can be simplified by using a matcher that accepts both None and any value:
```
decoy.when(
mock_instance.execute(
arg1=matchers.AnythingOrNone(),
arg2=matchers.AnythingOrNone(),
)
).then_return(self.some_result)
```
=> feat(matchers): add `AnythingOrNone` to match any value including `None`

decoy/matchers.py, tests/test_matchers.py
Add an `ArrayMatcher` to test that an array contains a sub-array
=> feat(matchers): add `ListMatching` to match sub-lists
